all:

	g++ -c DisplayAle.cpp -o display
	g++ -c Console.cpp -o console
	g++ -c KeyboardAle.cpp -o keyboard
	g++ -c KeyAle.cpp -o key
	g++ -c CpuAle.cpp -o cpu
	g++ main.cpp console display cpu keyboard key -o main
	./main